[workspace]
members = [".", "llvm-pass"]

[package]
name = "rsched"
version = "0.1.0"
edition = "2024"

[lib]
name = "rsched"
# rlib      – used by integration tests (Rust calls into our no_mangle exports)
# staticlib – C programs that statically link against librsched.a
crate-type = ["rlib", "staticlib"]
bench = false

[dependencies]
corosensei = "0.3.4"
libc = "0.2"

[dev-dependencies]
criterion = { version = "0.8", features = ["html_reports"] }

[features]
tsan = []
asan = []
coro = []
instrumented-libc = []

[build-dependencies]
cc = "1"

[[bench]]
name = "create"
harness = false

[[bench]]
name = "lock"
harness = false

[[bench]]
name = "counter"
harness = false

[[bench]]
name = "buffer"
harness = false
